name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: jc1525/blog-be
          stage: main
          yaml: >
            name: blog-be

            app: node@20

            options:
              env:
                - name: REFRESH_TOKEN_SECRET
                  value: 605ae0a2578aa7f2bff9c25a4373bbc9fc5ecf6619f9c38870fdd70948c739ad23986b347dd0afbedeeb5d0610966116f41c4e66e94354e595d9dbce361dfe21
                - name: ACCESS_TOKEN_SECRET
                  value: 737d3a413838ec477e8e675fcdda46b001b6f9af79f897925a9d665391faf75e8be79c9353009
                - name: DATABASE_URI
                  value: mongodb+srv://jc1525:5VQmodl1ySZC3o67@blog.nfjkwij.mongodb.net/?retryWrites=true&w=majority&appName=blog
                - name: PORT
                  value: "3000"
              ports: 3000
              install: npm install
              build: npm run build
              start: npm start
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
